stages:
 - deploy
 
deploy:
 stage: deploy
 image: alpine
 script:   
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY_INTERNAL" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh gitlab-runner@192.168.2.252 "sudo /root/backup.sh"
 only:
 - master
